/**
 * Flower catalog data — the single source of truth for every flower card shown
 * on the site. Rendering is fully data-driven: to add a variety, drop its
 * WebP files into `public/images/flowers/<family>/` (via `npm run
 * flowers:optimize`) and add an entry here. No UI/component changes required.
 *
 * Image convention: `image` is the size-less base path. The responsive WebP
 * variants live beside it as `<base>-<width>.webp`, generated by
 * scripts/optimize-flowers.mjs for each width in IMAGE_WIDTHS.
 */

export type Availability = 'in-stock' | 'seasonal' | 'coming-soon';

export interface Flower {
  id: string;
  family: string;
  name: string;
  slug: string;
  color: string;
  /** Size-less base path, e.g. "/images/flowers/alstroemeria/purple". */
  image: string;
  alt: string;
  category: string;
  availability: Availability;
  featured?: boolean;
  /** Indicative price in USD (store currency), e.g. per wholesale bunch. */
  price?: number;
  futurePrice?: number;
  description?: string;
}

/** Format an indicative USD price for display (store currency is USD). */
export function formatJmd(amount: number): string {
  return `$${amount.toFixed(2)}`;
}

/** Responsive widths emitted by the optimizer (mobile → retina desktop). */
export const IMAGE_WIDTHS = [200, 300, 400, 800] as const;

/** Intrinsic aspect box for every card image (sources are square). Prevents CLS. */
export const FLOWER_IMAGE_RATIO = {width: 400, height: 400} as const;

/** Build a `srcset` string from an entry's size-less base path. */
export function flowerSrcSet(base: string): string {
  return IMAGE_WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(', ');
}

/** Default `src` (mid size) for browsers without srcset support. */
export function flowerSrc(base: string): string {
  return `${base}-400.webp`;
}

/** Kebab family slug → catalog filter (never a 404; degrades to empty state). */
export function familyHandle(family: string): string {
  return family
    .toLowerCase()
    .replace(/['’]/g, '') // drop apostrophes so "Baby's Breath" → "babys-breath"
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function flowerHref(flower: Flower): string {
  return `/collections/all-flowers?flower=${familyHandle(flower.family)}`;
}

/** True when a family has uploaded colourway images in the catalog. */
export function hasFlowerImages(handle: string): boolean {
  return FLOWERS.some((f) => familyHandle(f.family) === handle);
}

/** Colourways for one family handle (empty if none uploaded yet). */
export function flowersForFamily(handle: string): Flower[] {
  return FLOWERS.filter((f) => familyHandle(f.family) === handle);
}

/**
 * Size-less base path for a category card's representative image, or null when
 * no imagery exists yet (→ the card renders an elegant placeholder). Defaults
 * to the featured colourway, else the first. Drop a family's colourways in via
 * the flower pipeline and its category card lights up automatically.
 */
/**
 * Explicit representative-image overrides (e.g. a mixed-bouquet hero) keyed by
 * family handle. Drop the file into the family folder and add its base path.
 */
const CATEGORY_IMAGE_OVERRIDE: Record<string, string> = {
  alstroemeria: '/images/flowers/alstroemeria/all',
  asters: '/images/flowers/asters/all',
  'babys-breath': '/images/flowers/babys-breath/all',
  'calla-lilies': '/images/flowers/calla-lilies/all',
  carnations: '/images/flowers/carnations/all',
  chrysanthemums: '/images/flowers/chrysanthemums/all',
  delphinium: '/images/flowers/delphinium/all',
  eucalyptus: '/images/flowers/eucalyptus/all',
  fillers: '/images/flowers/fillers/all',
  'gerbera-daisies': '/images/flowers/gerbera-daisies/all',
  'gift-bouquets': '/images/flowers/gift-bouquets/all',
  greenery: '/images/flowers/greenery/all',
  hydrangea: '/images/flowers/hydrangea/all',
  hypericum: '/images/flowers/hypericum/all',
  lilies: '/images/flowers/lilies/all',
  lisianthus: '/images/flowers/lisianthus/all',
  novelties: '/images/flowers/novelties/all',
  orchids: '/images/flowers/orchids/all',
  ranunculus: '/images/flowers/ranunculus/all',
  'roses-in-stock': '/images/flowers/roses-in-stock/all',
  snapdragon: '/images/flowers/snapdragon/all',
  'spray-roses': '/images/flowers/spray-roses/all',
  stock: '/images/flowers/stock/all',
  tropicals: '/images/flowers/tropicals/all',
  tulips: '/images/flowers/tulips/all',
};

export function categoryImageBase(handle: string): string | null {
  if (CATEGORY_IMAGE_OVERRIDE[handle]) return CATEGORY_IMAGE_OVERRIDE[handle];
  const set = flowersForFamily(handle);
  if (set.length === 0) return null;
  const featured = set.find((f) => f.featured) ?? set[0];
  return featured.image;
}

/**
 * Helper to declare a family's colorways tersely while keeping every field
 * explicit in the emitted objects (good for grep + SEO review).
 */
function family(
  name: string,
  colors: Array<{
    color: string;
    file: string;
    /** Editorial arrangement name; defaults to "<Color> <Family>". */
    label?: string;
    price?: number;
    description?: string;
    availability?: Availability;
    featured?: boolean;
  }>,
): Flower[] {
  const slugBase = familyHandle(name);
  return colors.map(
    ({color, file, label, price, description, availability = 'in-stock', featured}) => ({
      id: `${slugBase}-${file}`,
      family: name,
      name: label ?? `${color} ${name}`,
      slug: `${file}-${slugBase}`,
      color,
      image: `/images/flowers/${slugBase}/${file}`,
      alt: `${color} ${name} — fresh cut flowers from The New Greenhouse, Kingston, Jamaica`,
      category: name,
      availability,
      ...(price != null ? {price} : {}),
      ...(description ? {description} : {}),
      ...(featured ? {featured} : {}),
    }),
  );
}

export const FLOWERS: Flower[] = [
  // Alstroemeria — sold by the wholesale bunch (~10 stems). Indicative pricing.
  ...family('Alstroemeria', [
    {
      color: 'Purple',
      file: 'purple',
      label: 'Amethyst Alstroemeria Bunch',
      price: 28,
      description: 'Deep amethyst blooms with long, elegant vase life.',
      featured: true,
    },
    {
      color: 'Lavender',
      file: 'lavender',
      label: 'Lavender Mist Alstroemeria Bunch',
      price: 28,
      description: 'Soft lavender petals for romantic, airy arrangements.',
    },
    {
      color: 'Orange',
      file: 'orange',
      label: 'Sunset Alstroemeria Bunch',
      price: 27,
      description: 'Warm sunset orange — vivid, cheerful, long-lasting.',
    },
    {
      color: 'Pink',
      file: 'pink',
      label: 'Blush Alstroemeria Bunch',
      price: 28,
      description: 'Blush pink with a painterly throat; a bridal favourite.',
      featured: true,
    },
    {
      color: 'Red',
      file: 'red',
      label: 'Scarlet Alstroemeria Bunch',
      price: 30,
      description: 'Rich scarlet red for bold, statement bouquets.',
    },
    {
      color: 'White',
      file: 'white',
      label: 'Ivory Alstroemeria Bunch',
      price: 28,
      description: 'Pure ivory — sympathy, weddings, and clean modern work.',
    },
    {
      color: 'Yellow',
      file: 'yellow',
      label: 'Golden Alstroemeria Bunch',
      price: 27,
      description: 'Sunny golden yellow that lifts any mixed design.',
    },
  ]),
  ...family('Asters', [
    {color: 'Lavender', file: 'lavender'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
  ]),
  ...family("Baby’s Breath", [
    {color: 'White', file: 'white'},
  ]),
  ...family('Calla Lilies', [
    {color: 'Orange', file: 'orange'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Carnations', [
    {color: 'Burgundy', file: 'burgundy'},
    {color: 'Lavender', file: 'lavender'},
    {color: 'Peach', file: 'peach'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Chrysanthemums', [
    {color: 'Bronze', file: 'bronze'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Delphinium', [
    {color: 'Blue', file: 'blue'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
  ]),
  ...family('Eucalyptus', [
    {color: 'Baby Blue', file: 'baby-blue'},
    {color: 'Parvifolia', file: 'parvifolia'},
    {color: 'Seeded', file: 'seeded'},
    {color: 'Silver Dollar', file: 'silver-dollar'},
    {color: 'Willow', file: 'willow'},
  ]),
  ...family('Fillers', [
    {color: 'Green', file: 'green'},
    {color: 'Limonium', file: 'limonium', label: 'Limonium'},
    {color: 'Solidago', file: 'solidago', label: 'Solidago'},
    {color: 'Statice', file: 'statice-purple', label: 'Statice'},
    {color: 'Wax Flower', file: 'wax-flower-pink', label: 'Wax Flower'},
    {color: 'White', file: 'white'},
  ]),
  ...family('Gerbera Daisies', [
    {color: 'Orange', file: 'orange'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Gift Bouquets', [
    {color: 'Bright Mixed', file: 'bright', label: 'Bright Mixed'},
    {color: 'Mixed', file: 'mixed', label: 'Mixed'},
    {color: 'Pastel Mixed', file: 'pastel', label: 'Pastel Mixed'},
  ]),
  ...family('Greenery', [
    {color: 'Bear Grass', file: 'bear-grass', label: 'Bear Grass'},
    {color: 'Leatherleaf Fern', file: 'leatherleaf-fern', label: 'Leatherleaf Fern'},
    {color: 'Mixed', file: 'mixed', label: 'Mixed'},
    {color: 'Pittosporum', file: 'pittosporum', label: 'Pittosporum'},
    {color: 'Italian Ruscus', file: 'ruscus', label: 'Italian Ruscus'},
    {color: 'Salal', file: 'salal', label: 'Salal'},
  ]),
  ...family('Hydrangea', [
    {color: 'Blue', file: 'blue'},
    {color: 'Green', file: 'green'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
  ]),
  ...family('Hypericum', [
    {color: 'Burgundy', file: 'burgundy'},
    {color: 'Green', file: 'green'},
    {color: 'Ivory', file: 'ivory'},
    {color: 'Peach', file: 'peach'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
  ]),
  ...family('Lilies', [
    {color: 'Orange', file: 'orange'},
    {color: 'Pink', file: 'pink'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Lisianthus', [
    {color: 'Lavender', file: 'lavender'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
  ]),
  ...family('Novelties', [
    {color: 'Billy Balls', file: 'billy-balls', label: 'Billy Balls'},
    {color: 'Celosia', file: 'celosia', label: 'Celosia'},
    {color: 'Mixed', file: 'mixed', label: 'Mixed'},
    {color: 'Scabiosa Pods', file: 'scabiosa-pods', label: 'Scabiosa Pods'},
  ]),
  ...family('Orchids', [
    {color: 'Green', file: 'green'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Ranunculus', [
    {color: 'Orange', file: 'orange'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Roses - In Stock', [
    {color: 'Lavender', file: 'lavender'},
    {color: 'Orange', file: 'orange'},
    {color: 'Peach', file: 'peach'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Snapdragon', [
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Spray Roses', [
    {color: 'Peach', file: 'peach'},
    {color: 'Pink', file: 'pink'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
  ...family('Stock', [
    {color: 'Lavender', file: 'lavender'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'White', file: 'white'},
  ]),
  ...family('Tropicals', [
    {color: 'Pink Anthurium', file: 'anthurium-pink', label: 'Pink Anthurium'},
    {color: 'Red Anthurium', file: 'anthurium-red', label: 'Red Anthurium'},
    {color: 'Bird of Paradise', file: 'bird-of-paradise', label: 'Bird of Paradise'},
    {color: 'Ginger', file: 'ginger', label: 'Ginger'},
    {color: 'Heliconia', file: 'heliconia', label: 'Heliconia'},
    {color: 'Mixed', file: 'mixed', label: 'Mixed'},
    {color: 'Protea', file: 'protea', label: 'Protea'},
  ]),
  ...family('Tulips', [
    {color: 'Orange', file: 'orange'},
    {color: 'Pink', file: 'pink'},
    {color: 'Purple', file: 'purple'},
    {color: 'Red', file: 'red'},
    {color: 'White', file: 'white'},
    {color: 'Yellow', file: 'yellow'},
  ]),
];

/** Group flowers by family, preserving first-seen family order. */
export function flowersByFamily(list: Flower[] = FLOWERS): Array<{
  family: string;
  handle: string;
  flowers: Flower[];
}> {
  const order: string[] = [];
  const map = new Map<string, Flower[]>();
  for (const f of list) {
    if (!map.has(f.family)) {
      map.set(f.family, []);
      order.push(f.family);
    }
    map.get(f.family)!.push(f);
  }
  return order.map((fam) => ({
    family: fam,
    handle: familyHandle(fam),
    flowers: map.get(fam)!,
  }));
}
