/**
 * Flower catalog data — the single source of truth for every flower card shown
 * on the site. Rendering is fully data-driven: to add a variety, drop its
 * WebP files into `public/images/flowers/<family>/` (via `npm run
 * flowers:optimize`) and add an entry here. No UI/component changes required.
 *
 * Image convention: `image` is the size-less base path. The responsive WebP
 * variants live beside it as `<base>-<width>.webp`, generated by
 * scripts/optimize-flowers.mjs for each width in IMAGE_WIDTHS.
 */

export type Availability = 'in-stock' | 'seasonal' | 'coming-soon';

export interface Flower {
  id: string;
  family: string;
  name: string;
  slug: string;
  color: string;
  /** Size-less base path, e.g. "/images/flowers/alstroemeria/purple". */
  image: string;
  alt: string;
  category: string;
  availability: Availability;
  featured?: boolean;
  /** Indicative price in USD (store currency), e.g. per wholesale bunch. */
  price?: number;
  futurePrice?: number;
  description?: string;
}

/** Format an indicative USD price for display (store currency is USD). */
export function formatJmd(amount: number): string {
  return `$${amount.toFixed(2)}`;
}

/** Responsive widths emitted by the optimizer (mobile → retina desktop). */
export const IMAGE_WIDTHS = [200, 300, 400, 800] as const;

/** Intrinsic aspect box for every card image (sources are square). Prevents CLS. */
export const FLOWER_IMAGE_RATIO = {width: 400, height: 400} as const;

/** Build a `srcset` string from an entry's size-less base path. */
export function flowerSrcSet(base: string): string {
  return IMAGE_WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(', ');
}

/** Default `src` (mid size) for browsers without srcset support. */
export function flowerSrc(base: string): string {
  return `${base}-400.webp`;
}

/** Kebab family slug → catalog filter (never a 404; degrades to empty state). */
export function familyHandle(family: string): string {
  return family
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function flowerHref(flower: Flower): string {
  return `/collections/all-flowers?flower=${familyHandle(flower.family)}`;
}

/** True when a family has uploaded colourway images in the catalog. */
export function hasFlowerImages(handle: string): boolean {
  return FLOWERS.some((f) => familyHandle(f.family) === handle);
}

/** Colourways for one family handle (empty if none uploaded yet). */
export function flowersForFamily(handle: string): Flower[] {
  return FLOWERS.filter((f) => familyHandle(f.family) === handle);
}

/**
 * Size-less base path for a category card's representative image, or null when
 * no imagery exists yet (→ the card renders an elegant placeholder). Defaults
 * to the featured colourway, else the first. Drop a family's colourways in via
 * the flower pipeline and its category card lights up automatically.
 */
/**
 * Explicit representative-image overrides (e.g. a mixed-bouquet hero) keyed by
 * family handle. Drop the file into the family folder and add its base path.
 */
const CATEGORY_IMAGE_OVERRIDE: Record<string, string> = {
  alstroemeria: '/images/flowers/alstroemeria/all',
};

export function categoryImageBase(handle: string): string | null {
  if (CATEGORY_IMAGE_OVERRIDE[handle]) return CATEGORY_IMAGE_OVERRIDE[handle];
  const set = flowersForFamily(handle);
  if (set.length === 0) return null;
  const featured = set.find((f) => f.featured) ?? set[0];
  return featured.image;
}

/**
 * Helper to declare a family's colorways tersely while keeping every field
 * explicit in the emitted objects (good for grep + SEO review).
 */
function family(
  name: string,
  colors: Array<{
    color: string;
    file: string;
    /** Editorial arrangement name; defaults to "<Color> <Family>". */
    label?: string;
    price?: number;
    description?: string;
    availability?: Availability;
    featured?: boolean;
  }>,
): Flower[] {
  const slugBase = familyHandle(name);
  return colors.map(
    ({color, file, label, price, description, availability = 'in-stock', featured}) => ({
      id: `${slugBase}-${file}`,
      family: name,
      name: label ?? `${color} ${name}`,
      slug: `${file}-${slugBase}`,
      color,
      image: `/images/flowers/${slugBase}/${file}`,
      alt: `${color} ${name} — fresh cut flowers from The New Greenhouse, Kingston, Jamaica`,
      category: name,
      availability,
      ...(price != null ? {price} : {}),
      ...(description ? {description} : {}),
      ...(featured ? {featured} : {}),
    }),
  );
}

export const FLOWERS: Flower[] = [
  // Alstroemeria — sold by the wholesale bunch (~10 stems). Indicative pricing.
  ...family('Alstroemeria', [
    {
      color: 'Purple',
      file: 'purple',
      label: 'Amethyst Alstroemeria Bunch',
      price: 28,
      description: 'Deep amethyst blooms with long, elegant vase life.',
      featured: true,
    },
    {
      color: 'Lavender',
      file: 'lavender',
      label: 'Lavender Mist Alstroemeria Bunch',
      price: 28,
      description: 'Soft lavender petals for romantic, airy arrangements.',
    },
    {
      color: 'Orange',
      file: 'orange',
      label: 'Sunset Alstroemeria Bunch',
      price: 27,
      description: 'Warm sunset orange — vivid, cheerful, long-lasting.',
    },
    {
      color: 'Pink',
      file: 'pink',
      label: 'Blush Alstroemeria Bunch',
      price: 28,
      description: 'Blush pink with a painterly throat; a bridal favourite.',
      featured: true,
    },
    {
      color: 'Red',
      file: 'red',
      label: 'Scarlet Alstroemeria Bunch',
      price: 30,
      description: 'Rich scarlet red for bold, statement bouquets.',
    },
    {
      color: 'White',
      file: 'white',
      label: 'Ivory Alstroemeria Bunch',
      price: 28,
      description: 'Pure ivory — sympathy, weddings, and clean modern work.',
    },
    {
      color: 'Yellow',
      file: 'yellow',
      label: 'Golden Alstroemeria Bunch',
      price: 27,
      description: 'Sunny golden yellow that lifts any mixed design.',
    },
  ]),
];

/** Group flowers by family, preserving first-seen family order. */
export function flowersByFamily(list: Flower[] = FLOWERS): Array<{
  family: string;
  handle: string;
  flowers: Flower[];
}> {
  const order: string[] = [];
  const map = new Map<string, Flower[]>();
  for (const f of list) {
    if (!map.has(f.family)) {
      map.set(f.family, []);
      order.push(f.family);
    }
    map.get(f.family)!.push(f);
  }
  return order.map((fam) => ({
    family: fam,
    handle: familyHandle(fam),
    flowers: map.get(fam)!,
  }));
}
