import {Link, redirect, useLoaderData, useNavigation} from 'react-router';
import {useState, type ReactNode} from 'react';
import type {Route} from './+types/collections.$handle';
import {getPaginationVariables, Analytics} from '@shopify/hydrogen';
import type {
  ProductCollectionSortKeys,
  ProductFilter,
  ProductSortKeys,
} from '@shopify/hydrogen/storefront-api-types';
import {redirectIfHandleIsLocalized} from '~/lib/redirect';
import {
  parseCatalogSearchParams,
  buildProductFilters,
  buildProductQueryString,
  toCollectionSort,
  toCatalogSort,
  countActiveFilters,
  FACETS,
  CATALOG_PRODUCT_FRAGMENT,
} from '~/lib/catalog';
import type {CatalogImage, CatalogProduct} from '~/components/catalog/types';
import type {ExperienceMode} from '~/lib/experience';
import {CollectionHero} from '~/components/catalog/CollectionHero';
import {
  FilterPanel,
  FilterDrawer,
  ActiveFilterChips,
} from '~/components/catalog/Filters';
import {CatalogToolbar} from '~/components/catalog/CatalogToolbar';
import {CatalogResults} from '~/components/catalog/CatalogResults';
import {FlowerCategoryGrid} from '~/components/catalog/FlowerCategoryGrid';
import {QuickView} from '~/components/catalog/QuickView';
import {useExperience} from '~/components/ExperienceProvider';

/** Collections that use the visual category-browser experience. */
const FLOWER_HUBS = new Set(['bulk-flowers', 'all-flowers']);

/**
 * Deluxe collections with a dedicated wide (16:9) editorial hero banner in
 * /public/images/collection-heroes/<handle>-{800,1200,1600}.webp (generated by
 * scripts/images/collection-heroes.mjs). Overrides the Shopify `collection.image`
 * in the Deluxe experience only — several Deluxe collections had no image (text
 * hero) or a mismatched legacy banner (e.g. luxury-bouquets carried a "Birthday
 * Flowers" banner). Value is the alt text. Handles without an entry fall back to
 * a clean centered text hero. Classic is unaffected (it keeps `collection.image`).
 */
const DELUXE_COLLECTION_HERO: Record<string, string> = {
  'luxury-bouquets': 'A lush mixed garden bouquet of pastel roses and hydrangea',
  'best-sellers': 'An opulent deep red rose arrangement',
  'signature-collection': 'An ivory and blush rose bouquet',
  'seasonal-deluxe': 'A bold tropical arrangement of bird of paradise and orchids',
  'thank-you': 'A peach and cream thank-you rose bouquet',
  roses: 'Premium red and blush garden roses',
  orchids: 'Tall white phalaenopsis orchid stems',
  anniversary: 'Blush and ivory anniversary roses',
  birthday: 'Bright mixed birthday blooms',
  'love-and-romance': 'Deep red romance roses',
  'sympathy-and-funeral': 'Serene white lilies and roses',
  congratulations: 'Vibrant celebratory blooms',
  'get-well': 'Cheerful yellow and white blooms',
  'new-baby': 'Soft pastel new-baby blooms',
  'corporate-gifting': 'White roses with premium foliage',
  'bridal-bouquets': 'An elegant white bridal bouquet',
};

/**
 * Choose the collection hero media. Deluxe prefers its dedicated wide banner
 * (see DELUXE_COLLECTION_HERO); otherwise both experiences use the Shopify
 * `collection.image`, falling back to a clean text hero when there is none.
 */
function collectionHeroImage(
  experience: ExperienceMode,
  collection: {
    handle: string;
    image?: {url: string; altText?: string | null} | null;
  },
): CatalogImage | ReactNode | undefined {
  if (experience === 'deluxe') {
    const alt = DELUXE_COLLECTION_HERO[collection.handle];
    if (alt) {
      const base = `/images/collection-heroes/${collection.handle}`;
      return (
        <img
          className="ng-catalog-hero-img"
          src={`${base}-1200.webp`}
          srcSet={`${base}-800.webp 800w, ${base}-1200.webp 1200w, ${base}-1600.webp 1600w`}
          sizes="100vw"
          alt={alt}
          loading="eager"
        />
      );
    }
  }
  return collection.image
    ? {url: collection.image.url, altText: collection.image.altText}
    : undefined;
}

/**
 * Deluxe collections that are part of the approved journey but not yet created
 * in Shopify Admin. Rather than 404, the loader renders a safe, empty, on-brand
 * collection page so the Deluxe experience is complete and never falls back to a
 * shared collection that could leak wholesale products. Populate these in Admin
 * (see docs/FOCUSED_DUAL_STORE_FINAL_QA.md → Remaining Shopify Admin tasks) and
 * remove the handle here once live.
 */
const PLANNED_COLLECTIONS: Record<string, {title: string; description: string}> =
  {
    'seasonal-deluxe': {
      title: 'Seasonal Deluxe',
      description:
        'Our seasonal luxury edit is being curated. Explore Signature Bouquets and Premium Flowers in the meantime.',
    },
  };

function flowerLabelFor(handle?: string): string | undefined {
  if (!handle) return undefined;
  return FACETS.find((f) => f.key === 'flower')?.options.find(
    (o) => o.value === handle,
  )?.label;
}

export const meta: Route.MetaFunction = ({data}) => {
  const isHub = data ? FLOWER_HUBS.has(data.collection.handle) : false;
  // Title syncs with the active flower, else "All Flowers" on a hub, else the
  // collection's own title.
  const title =
    data?.flowerLabel ||
    (isHub ? 'All Flowers' : data?.collection?.seo?.title || data?.collection?.title) ||
    'Collection';
  const description =
    data?.collection?.seo?.description ||
    data?.collection?.description ||
    'Shop luxury and wholesale floral arrangements from The New Greenhouse in Kingston, Jamaica.';
  const fullTitle = `${title} | The New Greenhouse`;
  const origin = data?.origin ?? '';
  const path = data?.collection?.handle
    ? `/collections/${data.collection.handle}`
    : '';
  const image = data?.collection?.image?.url;
  return [
    {title: fullTitle},
    {name: 'description', content: description},
    {property: 'og:type', content: 'website'},
    {property: 'og:title', content: fullTitle},
    {property: 'og:description', content: description},
    {property: 'og:url', content: `${origin}${path}`},
    {property: 'og:site_name', content: 'The New Greenhouse'},
    {name: 'twitter:card', content: 'summary_large_image'},
    {name: 'twitter:title', content: fullTitle},
    {name: 'twitter:description', content: description},
    ...(image
      ? [
          {property: 'og:image' as const, content: image},
          {name: 'twitter:image' as const, content: image},
        ]
      : []),
    // Canonical to the base collection: filtered/faceted views (?flower=…,
    // ?sort=…) canonicalize here so they aren't indexed as duplicates. The
    // per-variety /flowers/$family routes carry the indexable variety SEO.
    ...(path
      ? [{tagName: 'link' as const, rel: 'canonical', href: path}]
      : []),
  ];
};

export async function loader(args: Route.LoaderArgs) {
  const deferredData = loadDeferredData(args);
  const criticalData = await loadCriticalData(args);
  return {...deferredData, ...criticalData};
}

async function loadCriticalData({context, params, request}: Route.LoaderArgs) {
  const {handle} = params;
  const {storefront} = context;

  if (!handle) {
    throw redirect('/collections');
  }

  const url = new URL(request.url);
  const {filters: applied, sort} = parseCatalogSearchParams(url.searchParams);
  const productFilters = buildProductFilters(applied);
  const {sortKey, reverse} = toCollectionSort(sort);
  const paginationVariables = getPaginationVariables(request, {pageBy: 12});

  const isHub = FLOWER_HUBS.has(handle);
  // On a flower hub, the per-variety product view uses the top-level product
  // search (query:"tag:'flower:X'"), which filters reliably — the Storefront
  // `collection.products(filters:)` argument is ignored unless the collection
  // has tag filters enabled in Shopify's Search & Discovery settings.
  const catSort = toCatalogSort(sort);
  const flowerPromise =
    isHub && applied.flower
      ? storefront.query(HUB_PRODUCTS_QUERY, {
          variables: {
            query: buildProductQueryString(applied),
            sortKey: catSort.sortKey as ProductSortKeys,
            reverse: catSort.reverse,
            ...paginationVariables,
          },
        })
      : Promise.resolve(null);

  const [{collection}, flowerResult] = await Promise.all([
    storefront.query(COLLECTION_QUERY, {
      variables: {
        handle,
        filters: productFilters,
        sortKey: sortKey as ProductCollectionSortKeys,
        reverse,
        ...paginationVariables,
      },
    }),
    flowerPromise,
  ]);

  if (!collection) {
    // Approved-but-not-yet-created Deluxe collection → safe empty state, no 404,
    // no wholesale fallback.
    const planned = PLANNED_COLLECTIONS[handle];
    if (planned) {
      return {
        collection: {
          id: `planned:${handle}`,
          handle,
          title: planned.title,
          description: planned.description,
          image: null,
          seo: {title: planned.title, description: planned.description},
          products: {
            nodes: [],
            pageInfo: {
              hasPreviousPage: false,
              hasNextPage: false,
              startCursor: null,
              endCursor: null,
            },
          },
          // Shape matches the CollectionQuery result the route consumes; the
          // unused query-only fields are intentionally omitted.
        } as unknown as NonNullable<typeof collection>,
        applied,
        sort,
        flowerLabel: undefined,
        flowerProducts: null,
      };
    }
    throw new Response(`Collection ${handle} not found`, {status: 404});
  }

  redirectIfHandleIsLocalized(request, {handle, data: collection});

  return {
    collection,
    applied,
    sort,
    flowerLabel: flowerLabelFor(applied.flower),
    flowerProducts: flowerResult?.products ?? null,
    origin: url.origin,
  };
}

function loadDeferredData({context}: Route.LoaderArgs) {
  return {};
}

export default function Collection() {
  const {collection, applied, sort, flowerLabel, flowerProducts} =
    useLoaderData<typeof loader>();
  const navigation = useNavigation();
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [quickProduct, setQuickProduct] = useState<CatalogProduct | null>(null);

  const loading = navigation.state !== 'idle';
  const activeCount = countActiveFilters(applied);

  const {experience} = useExperience();
  const isHub = FLOWER_HUBS.has(collection.handle);
  const activeFlower = applied.flower;
  const hubPath = `/collections/${collection.handle}`;
  // Deluxe non-hub collections use an editorial, full-width layout (no permanent
  // filter rail) — the wholesale faceted sidebar reads like a supply catalogue.
  // Filtering stays available via the toolbar's slide-out drawer.
  const editorial = experience === 'deluxe' && !isHub;
  const heroEyebrow = isHub
    ? experience === 'deluxe'
      ? 'The Signature Collection'
      : 'Wholesale Flowers'
    : 'The Collection';

  // Hub flower views use the top-level product search connection (reliable tag
  // filtering); everything else uses the collection's own products.
  const productConnection =
    isHub && activeFlower && flowerProducts ? flowerProducts : collection.products;
  const products = (productConnection.nodes ?? []) as CatalogProduct[];

  // On a flower hub the default view is the visual category browser ("All
  // Flowers"); picking a variety (card or sidebar) switches to its products.
  const showCategoryBrowser = isHub && !activeFlower;
  const heading = activeFlower
    ? flowerLabel ?? collection.title
    : isHub
      ? 'All Flowers'
      : collection.title;

  const breadcrumbs = [
    {label: 'Home', to: '/'},
    {label: 'Collections', to: '/collections'},
    ...(isHub
      ? activeFlower
        ? [{label: 'All Flowers', to: hubPath}, {label: heading}]
        : [{label: 'All Flowers'}]
      : [{label: collection.title}]),
  ];

  return (
    <div className="ng-catalog-page">
      <CollectionHero
        breadcrumbs={breadcrumbs}
        eyebrow={heroEyebrow}
        title={heading}
        description={collection.description || undefined}
        image={collectionHeroImage(experience, collection)}
      />

      <div
        className={
          editorial
            ? 'ng-catalog-layout ng-catalog-layout--editorial'
            : 'ng-catalog-layout'
        }
      >
        {editorial ? null : (
          <aside className="ng-catalog-sidebar" aria-label="Product filters">
            <FilterPanel variant="sidebar" filters={applied} />
          </aside>
        )}

        <div className="ng-catalog-main">
          {showCategoryBrowser ? (
            <section aria-label="Flower categories">
              <div className="ng-cat-intro">
                <h2 className="ng-cat-intro-title">Browse by variety</h2>
                <p className="ng-cat-intro-note">
                  Select a flower to view available stems — or refine with the
                  filters.
                </p>
              </div>
              <FlowerCategoryGrid
                collectionHandle={collection.handle}
                activeFlower={activeFlower}
              />
            </section>
          ) : (
            <>
              {isHub ? (
                <Link className="ng-cat-back" to={hubPath} preventScrollReset>
                  All flowers
                </Link>
              ) : null}
              <CatalogToolbar
                count={products.length}
                sort={sort}
                activeCount={activeCount}
                onOpenFilters={() => setDrawerOpen(true)}
              />
              <ActiveFilterChips filters={applied} />
              <CatalogResults
                connection={productConnection}
                loading={loading}
                hasFilters={activeCount > 0}
                onQuickView={setQuickProduct}
              />
            </>
          )}
        </div>
      </div>

      <FilterDrawer
        filters={applied}
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
      />
      <QuickView
        product={quickProduct}
        open={Boolean(quickProduct)}
        onClose={() => setQuickProduct(null)}
      />

      <Analytics.CollectionView
        data={{collection: {id: collection.id, handle: collection.handle}}}
      />
    </div>
  );
}

const COLLECTION_QUERY = `#graphql
  ${CATALOG_PRODUCT_FRAGMENT}
  query Collection(
    $handle: String!
    $country: CountryCode
    $language: LanguageCode
    $filters: [ProductFilter!]
    $sortKey: ProductCollectionSortKeys!
    $reverse: Boolean
    $first: Int
    $last: Int
    $startCursor: String
    $endCursor: String
  ) @inContext(country: $country, language: $language) {
    collection(handle: $handle) {
      id
      handle
      title
      description
      image {
        id
        url
        altText
        width
        height
      }
      seo {
        title
        description
      }
      products(
        first: $first
        last: $last
        before: $startCursor
        after: $endCursor
        filters: $filters
        sortKey: $sortKey
        reverse: $reverse
      ) {
        nodes {
          ...CatalogProductItem
        }
        pageInfo {
          hasPreviousPage
          hasNextPage
          endCursor
          startCursor
        }
      }
    }
  }
` as const;

// Reliable tag-based product search for the hub's per-variety view.
const HUB_PRODUCTS_QUERY = `#graphql
  ${CATALOG_PRODUCT_FRAGMENT}
  query HubProducts(
    $country: CountryCode
    $language: LanguageCode
    $query: String
    $sortKey: ProductSortKeys!
    $reverse: Boolean
    $first: Int
    $last: Int
    $startCursor: String
    $endCursor: String
  ) @inContext(country: $country, language: $language) {
    products(
      first: $first
      last: $last
      before: $startCursor
      after: $endCursor
      query: $query
      sortKey: $sortKey
      reverse: $reverse
    ) {
      nodes {
        ...CatalogProductItem
      }
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
    }
  }
` as const;
